{
	"spriteSheetClassPath" : "spritesheets/tiles.png",
	"spriteMap" : {
		"slate" : [ 0, 0 ],
		"bridg" : [ 1, 0 ],
		"dirty" : [ 2, 0 ],
		"plank" : [ 3, 0 ],
		"clear" : [ 4, 0 ],
		"rockk" : [ 5, 0 ],
		"gravl" : [ 6, 0 ],
		"stone" : [ 0, 1 ],
		"soill" : [ 1, 1 ],
		"scrat" : [ 2, 1 ],
		"woven" : [ 3, 1 ],
		"black" : [ 4, 1 ],
		"sandd" : [ 5, 1 ],
		"slice" : [ 6, 1 ],
		"clayy" : [ 0, 2 ],
		"grass" : [ 1, 2 ],
		"pebbl" : [ 2, 2 ],
		"hedge" : [ 3, 2 ],
		"tiles" : [ 4, 2 ],
		"water" : [ 5, 2 ],
		"grayy" : [ 6, 2 ],
		"redtl" : [ 0, 3 ],
		"iceee" : [ 1, 3 ],
		"airrr" : [ 2, 3 ],
		"lavaa" : [ 3, 3 ],
		"snoww" : [ 4, 3 ],
		"puzz0" : [ 5, 3 ],
		"puzz1" : [ 6, 3 ],
		"puzz2" : [ 0, 4 ],
		"puzz3" : [ 1, 4 ],
		"plain" : [ 2, 4 ],
		"white" : [ 3, 4 ],
		"balsa" : [ 4, 4 ],
		"puzz4" : [ 0, 5 ],
		"rooff" : [ 1, 5 ],
		"flame" : [ 2, 5 ],
		"woody" : [ 3, 5 ],
		"marbl" : [ 0, 6 ],
		"grate" : [ 1, 6 ],
		"smoky" : [ 2, 6 ],
		"loggg" : [ 3, 6 ]
	}
}